name: get daily trend baseline data
'on':
  workflow_dispatch:
    inputs:
      geo:
        description: geo
        type: enviroment
        required: false
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Google Chrome (<<parameters.channel>>)
        run: |
          echo "Installing Chrome (<<parameters.channel>>) v<<parameters.version>>"
          wget -O /usr/src/google-chrome-<<parameters.channel>>_<<parameters.version>>_amd64.deb "http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-<<parameters.channel>>/google-chrome-<<parameters.channel>>_<<parameters.version>>-1_amd64.deb" && \
          dpkg -i /usr/src/google-chrome-<<parameters.channel>>_<<parameters.version>>_amd64.deb ; \
          apt-get install -f -y && \
          rm -f /usr/src/google-chrome-<<parameters.channel>>_<<parameters.version>>_amd64.deb
          echo "Location of Google Chrome Installation: `which google-chrome-<<parameters.channel>>`"
          echo "Google Chrome Version: `google-chrome-<<parameters.channel>> --version`"
      - name: Install dependencies
        run: |
          sudo apt-get update      
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run demo
        run: |
          python  getbaseline.py
        env:
          geo: '${{ github.event.inputs.geo }}'
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ github.run_id }}'
          prerelease: false
          title: '${{ github.run_id }}'
          files: |
            ./*             
