# .github/workflows/trend_analysis.yml

name: Run Google Trends Analysis with Gemini

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job runs the analysis script
  run-analysis:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest major version

      # Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5 # Use the latest major version
        with:
          python-version: '3.10' # Specify your desired Python version

      # Installs dependencies using pip and requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs the Python script
      # Passes the Gemini API Key from GitHub Secrets as an environment variable
      - name: Run Trend Analysis Script
        env:
          # IMPORTANT: The secret name here MUST match the name you created in GitHub Secrets
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python analyze_trends.py # Replace 'analyze_trends.py' with your actual script name
